import React from "react";
const logo = "/logo.png";

export const metadata = {
  icons: logo,
  title: "About Us",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
  return <>{children}</>;
}
