import axios from "axios";
import FullArticle from "@components/Article/FullArticle";
const logo = "/main/logo.png";

// export const metadata = {
//   icons: logo,
//   title: "Nextjs Blog",
//   description: "Generated by create next app",
// };

export async function generateMetadata({ params }) {
  const { articleId } = await params;
  // console.log(articleId);

  try {
    const article = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/api/article/${articleId}`
    );

    const articleData = article?.data;
    // console.log(articleData);

    return {
      title: articleData?.title,
      icons: logo,
      description: articleData?.description,
    };
  } catch (error) {
    console.error("Error fetching article metadata:", error.message);

    return {
      title: "404 - Page not found",
      icons: logo,
      description: "Page unavailable",
    };
  }
}

export default function FullArticlePage({ params }) {
  return <FullArticle params={params} />;
}
