import "../styles/globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Copyright from "@/components/Copyright";
import StoreProvider from "@/lib/StoreProvider";
const logo = "/logo.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  icons: logo,
  title: "Nextjs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
          <Copyright />
        </body>
      </html>
    </StoreProvider>
  );
}
