import React from "react";
import FullArticle from "./FullArticle";
import axios from "axios";
const logo = "/logo.png";

// export const metadata = {
//   icons: logo,
//   title: "Nextjs Blog",
//   description: "Generated by create next app",
// };

export async function generateMetadata({ params }) {
  const { articleId } = await params;

  try {
    const article = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/article/${articleId}`
    );

    const articleData = article.data;

    return {
      title: articleData.title,
      icons: logo,
      description: articleData.description.substring(0, 100),
    };
  } catch (error) {
    console.error("Error fetching article metadata:", error.message);

    return {
      title: "Nextjs Blog",
      icons: logo,
      description: "Generated by create next app",
    };
  }
}

export default function FullArticlePage({ params }) {
  return <FullArticle params={params} />;
}
